name: Sample CI
on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.0
      - name: Setup Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v6.0.0
        with:
          go-version: '1.23.x'
      - name: Install Go dependencies
        run: |
          cd functions/Func_Jobs
          go get .
          cd ../job_history
          go get .
      - name: Build Go functions
        run: |
          go build -C functions/Func_Jobs
          go build -C functions/job_history
      - name: Use Node 22
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: ui/pages/scalable-rtr-react/yarn.lock
      - name: Run yarn install
        uses: borales/actions-yarn@2a18ac083c150a32c8ae27a3d68fc8f77b2ad4be # v5.3.0
        with:
          cmd: install
          dir: ui/pages/scalable-rtr-react
      - name: Build React app
        uses: borales/actions-yarn@2a18ac083c150a32c8ae27a3d68fc8f77b2ad4be # v5.3.0
        with:
          cmd: build
          dir: ui/pages/scalable-rtr-react
      - name: Test the React app
        uses: borales/actions-yarn@2a18ac083c150a32c8ae27a3d68fc8f77b2ad4be # v5.3.0
        with:
          cmd: test
          dir: ui/pages/scalable-rtr-react
