name: Sample CI
on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.1.0
        with:
          go-version: '1.23.x'
      - name: Install Go dependencies
        run: |
          cd functions/Func_Jobs
          go get .
          cd ../job_history
          go get .
      - name: Build Go functions
        run: |
          go build -C functions/Func_Jobs
          go build -C functions/job_history
      - name: Use Node 22
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: ui/pages/scalable-rtr-react/yarn.lock
      - name: Run yarn install
        uses: borales/actions-yarn@2a18ac083c150a32c8ae27a3d68fc8f77b2ad4be # v5.3.0
        with:
          cmd: install
          dir: ui/pages/scalable-rtr-react
      - name: Build React app
        uses: borales/actions-yarn@2a18ac083c150a32c8ae27a3d68fc8f77b2ad4be # v5.3.0
        with:
          cmd: build
          dir: ui/pages/scalable-rtr-react
      - name: Test the React app
        uses: borales/actions-yarn@2a18ac083c150a32c8ae27a3d68fc8f77b2ad4be # v5.3.0
        with:
          cmd: test
          dir: ui/pages/scalable-rtr-react
